create_clock -period 10.000 -waveform {0.000 5.000} [get_ports clk]

set_property PACKAGE_PIN A18 [get_ports rst_n]
set_property PACKAGE_PIN E19 [get_ports yaz_hata_o]
set_property PACKAGE_PIN K18 [get_ports yaz_komut_i]
set_property PACKAGE_PIN H19 [get_ports oku_hata_o]
set_property PACKAGE_PIN V15 [get_ports {oku_adres_i[8]}]
set_property PACKAGE_PIN W17 [get_ports {oku_adres_i[9]}]
set_property PACKAGE_PIN V17 [get_ports {oku_adres_i[11]}]
set_property PACKAGE_PIN U14 [get_ports {oku_adres_i[0]}]
set_property PACKAGE_PIN V14 [get_ports {oku_adres_i[1]}]
set_property PACKAGE_PIN W16 [get_ports {oku_adres_i[10]}]
set_property PACKAGE_PIN G19 [get_ports {oku_veri_o[7]}]
set_property PACKAGE_PIN L18 [get_ports {oku_veri_o[0]}]
set_property PACKAGE_PIN W15 [get_ports {oku_adres_i[7]}]
set_property PACKAGE_PIN J17 [get_ports {oku_veri_o[2]}]
set_property PACKAGE_PIN H17 [get_ports {oku_veri_o[6]}]
set_property PACKAGE_PIN K19 [get_ports {oku_veri_o[4]}]
set_property PACKAGE_PIN M18 [get_ports {yaz_veri_i[4]}]
set_property PACKAGE_PIN U19 [get_ports {yaz_adres_i[8]}]
set_property PACKAGE_PIN U17 [get_ports {yaz_adres_i[2]}]
set_property PACKAGE_PIN P17 [get_ports {yaz_adres_i[11]}]
set_property PACKAGE_PIN P18 [get_ports {yaz_adres_i[10]}]
set_property PACKAGE_PIN K17 [get_ports {yaz_veri_i[1]}]
set_property PACKAGE_PIN T17 [get_ports {yaz_adres_i[4]}]
set_property PACKAGE_PIN L17 [get_ports {yaz_veri_i[2]}]
set_property PACKAGE_PIN R19 [get_ports {yaz_veri_i[5]}]
set_property PACKAGE_PIN R18 [get_ports {yaz_adres_i[9]}]
set_property PACKAGE_PIN U18 [get_ports {yaz_adres_i[1]}]
set_property PACKAGE_PIN N19 [get_ports {yaz_veri_i[7]}]
set_property PACKAGE_PIN P19 [get_ports {yaz_veri_i[6]}]
set_property PACKAGE_PIN T18 [get_ports {yaz_adres_i[3]}]
set_property PACKAGE_PIN N17 [get_ports {yaz_veri_i[0]}]
set_property PACKAGE_PIN W18 [get_ports {yaz_adres_i[6]}]
set_property PACKAGE_PIN W19 [get_ports {yaz_adres_i[5]}]
set_property PACKAGE_PIN V16 [get_ports {yaz_adres_i[0]}]
set_property PACKAGE_PIN M19 [get_ports {yaz_veri_i[3]}]
set_property PACKAGE_PIN V19 [get_ports {yaz_adres_i[7]}]
set_property PACKAGE_PIN J19 [get_ports {oku_veri_o[3]}]
set_property PACKAGE_PIN G17 [get_ports {oku_veri_o[5]}]
set_property PACKAGE_PIN W13 [get_ports {oku_adres_i[6]}]
set_property PACKAGE_PIN W14 [get_ports {oku_adres_i[5]}]
set_property PACKAGE_PIN J18 [get_ports {oku_veri_o[1]}]
set_property PACKAGE_PIN V13 [get_ports {oku_adres_i[2]}]
set_property PACKAGE_PIN U15 [get_ports {oku_adres_i[4]}]
set_property PACKAGE_PIN U16 [get_ports {oku_adres_i[3]}]
set_property PACKAGE_PIN C15 [get_ports clk]
set_property PACKAGE_PIN N18 [get_ports oku_komut_i]

set_property IOSTANDARD LVCMOS33 [get_ports {get_iobanks 14}]
set_property IOSTANDARD LVCMOS33 [get_ports {get_iobanks 16}]